version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB}
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  postgres-test:
    image: postgres
    ports:
      - '${POSTGRES_TEST_PORT}:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${TEST_DB}



volumes:
  postgres:
